// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVzk8DvHJvnVtRikUdxROYN1KKe07ue0',
    appId: '1:275135791976:web:db64da56d4a2f513418cdd',
    messagingSenderId: '275135791976',
    projectId: 'snow-paradise',
    authDomain: 'snow-paradise.firebaseapp.com',
    storageBucket: 'snow-paradise.firebasestorage.app',
    measurementId: 'G-3PM6TMEJPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_BHmrAdq7kaULuGfbk8aUW8RUDx9pQGA',
    appId: '1:275135791976:android:07fd0f4f7ef33b6b418cdd',
    messagingSenderId: '275135791976',
    projectId: 'snow-paradise',
    storageBucket: 'snow-paradise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqZwEajfNamI-3SId-rCQH6a4OIi-wLMo',
    appId: '1:275135791976:ios:ae0527451cf9b3f7418cdd',
    messagingSenderId: '275135791976',
    projectId: 'snow-paradise',
    storageBucket: 'snow-paradise.firebasestorage.app',
    iosBundleId: 'com.example.snowParadise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqZwEajfNamI-3SId-rCQH6a4OIi-wLMo',
    appId: '1:275135791976:ios:ae0527451cf9b3f7418cdd',
    messagingSenderId: '275135791976',
    projectId: 'snow-paradise',
    storageBucket: 'snow-paradise.firebasestorage.app',
    iosBundleId: 'com.example.snowParadise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQVzk8DvHJvnVtRikUdxROYN1KKe07ue0',
    appId: '1:275135791976:web:d28703d98d05b4ec418cdd',
    messagingSenderId: '275135791976',
    projectId: 'snow-paradise',
    authDomain: 'snow-paradise.firebaseapp.com',
    storageBucket: 'snow-paradise.firebasestorage.app',
    measurementId: 'G-N0J6Q93PNH',
  );
}
